//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/Scripts/StarControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/StarControls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @StarControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @StarControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""StarControls"",
    ""maps"": [
        {
            ""name"": ""SHIP"",
            ""id"": ""e22bcc79-a01e-43fb-8e46-8b7605354d0b"",
            ""actions"": [
                {
                    ""name"": ""TURN"",
                    ""type"": ""Value"",
                    ""id"": ""df1fb065-4870-493b-b93a-1eef52b3da69"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ROLL"",
                    ""type"": ""Value"",
                    ""id"": ""83b0854d-18a3-4741-9bf3-cddce93fef5e"",
                    ""expectedControlType"": ""Analog"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DRIVE"",
                    ""type"": ""Button"",
                    ""id"": ""2fbcbac0-98ee-4935-b054-46843507174a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BRAKE"",
                    ""type"": ""Button"",
                    ""id"": ""b678d7b0-697f-4f05-b704-a575e95b8a07"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LOOK"",
                    ""type"": ""Value"",
                    ""id"": ""c8b8fc81-be98-4320-a5cb-bd1c559c42f3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""ca76b71e-a310-473a-8ce3-c725d66c4eeb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TURN"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e0fbfcce-aaaa-4ccf-b8a3-79df19b086fd"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TURN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2d52629f-6773-4834-aaab-d74600e6deae"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TURN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a9ede753-b49c-4926-b879-c15864ade92b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TURN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3f95241b-acd7-4b11-ba5b-36503f79ca66"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TURN"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""bbb85a3c-bced-4af2-b936-5c174aa89d4b"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ROLL"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""76771b99-1c23-4c55-a0f8-9ced760fe281"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ROLL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""19c1a134-b39a-4cf4-9f47-0b26b2870794"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ROLL"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9238bdbf-4ddb-49b8-ac27-3786a908b8ae"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DRIVE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7970e78a-0789-4fd9-a6c3-1c3b80c5b89d"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BRAKE"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1e7f918-ccab-4f94-bc14-845f7e076d65"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LOOK"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // SHIP
        m_SHIP = asset.FindActionMap("SHIP", throwIfNotFound: true);
        m_SHIP_TURN = m_SHIP.FindAction("TURN", throwIfNotFound: true);
        m_SHIP_ROLL = m_SHIP.FindAction("ROLL", throwIfNotFound: true);
        m_SHIP_DRIVE = m_SHIP.FindAction("DRIVE", throwIfNotFound: true);
        m_SHIP_BRAKE = m_SHIP.FindAction("BRAKE", throwIfNotFound: true);
        m_SHIP_LOOK = m_SHIP.FindAction("LOOK", throwIfNotFound: true);
    }

    ~@StarControls()
    {
        UnityEngine.Debug.Assert(!m_SHIP.enabled, "This will cause a leak and performance issues, StarControls.SHIP.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SHIP
    private readonly InputActionMap m_SHIP;
    private List<ISHIPActions> m_SHIPActionsCallbackInterfaces = new List<ISHIPActions>();
    private readonly InputAction m_SHIP_TURN;
    private readonly InputAction m_SHIP_ROLL;
    private readonly InputAction m_SHIP_DRIVE;
    private readonly InputAction m_SHIP_BRAKE;
    private readonly InputAction m_SHIP_LOOK;
    /// <summary>
    /// Provides access to input actions defined in input action map "SHIP".
    /// </summary>
    public struct SHIPActions
    {
        private @StarControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public SHIPActions(@StarControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "SHIP/TURN".
        /// </summary>
        public InputAction @TURN => m_Wrapper.m_SHIP_TURN;
        /// <summary>
        /// Provides access to the underlying input action "SHIP/ROLL".
        /// </summary>
        public InputAction @ROLL => m_Wrapper.m_SHIP_ROLL;
        /// <summary>
        /// Provides access to the underlying input action "SHIP/DRIVE".
        /// </summary>
        public InputAction @DRIVE => m_Wrapper.m_SHIP_DRIVE;
        /// <summary>
        /// Provides access to the underlying input action "SHIP/BRAKE".
        /// </summary>
        public InputAction @BRAKE => m_Wrapper.m_SHIP_BRAKE;
        /// <summary>
        /// Provides access to the underlying input action "SHIP/LOOK".
        /// </summary>
        public InputAction @LOOK => m_Wrapper.m_SHIP_LOOK;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_SHIP; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="SHIPActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(SHIPActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="SHIPActions" />
        public void AddCallbacks(ISHIPActions instance)
        {
            if (instance == null || m_Wrapper.m_SHIPActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SHIPActionsCallbackInterfaces.Add(instance);
            @TURN.started += instance.OnTURN;
            @TURN.performed += instance.OnTURN;
            @TURN.canceled += instance.OnTURN;
            @ROLL.started += instance.OnROLL;
            @ROLL.performed += instance.OnROLL;
            @ROLL.canceled += instance.OnROLL;
            @DRIVE.started += instance.OnDRIVE;
            @DRIVE.performed += instance.OnDRIVE;
            @DRIVE.canceled += instance.OnDRIVE;
            @BRAKE.started += instance.OnBRAKE;
            @BRAKE.performed += instance.OnBRAKE;
            @BRAKE.canceled += instance.OnBRAKE;
            @LOOK.started += instance.OnLOOK;
            @LOOK.performed += instance.OnLOOK;
            @LOOK.canceled += instance.OnLOOK;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="SHIPActions" />
        private void UnregisterCallbacks(ISHIPActions instance)
        {
            @TURN.started -= instance.OnTURN;
            @TURN.performed -= instance.OnTURN;
            @TURN.canceled -= instance.OnTURN;
            @ROLL.started -= instance.OnROLL;
            @ROLL.performed -= instance.OnROLL;
            @ROLL.canceled -= instance.OnROLL;
            @DRIVE.started -= instance.OnDRIVE;
            @DRIVE.performed -= instance.OnDRIVE;
            @DRIVE.canceled -= instance.OnDRIVE;
            @BRAKE.started -= instance.OnBRAKE;
            @BRAKE.performed -= instance.OnBRAKE;
            @BRAKE.canceled -= instance.OnBRAKE;
            @LOOK.started -= instance.OnLOOK;
            @LOOK.performed -= instance.OnLOOK;
            @LOOK.canceled -= instance.OnLOOK;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="SHIPActions.UnregisterCallbacks(ISHIPActions)" />.
        /// </summary>
        /// <seealso cref="SHIPActions.UnregisterCallbacks(ISHIPActions)" />
        public void RemoveCallbacks(ISHIPActions instance)
        {
            if (m_Wrapper.m_SHIPActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="SHIPActions.AddCallbacks(ISHIPActions)" />
        /// <seealso cref="SHIPActions.RemoveCallbacks(ISHIPActions)" />
        /// <seealso cref="SHIPActions.UnregisterCallbacks(ISHIPActions)" />
        public void SetCallbacks(ISHIPActions instance)
        {
            foreach (var item in m_Wrapper.m_SHIPActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SHIPActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="SHIPActions" /> instance referencing this action map.
    /// </summary>
    public SHIPActions @SHIP => new SHIPActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "SHIP" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="SHIPActions.AddCallbacks(ISHIPActions)" />
    /// <seealso cref="SHIPActions.RemoveCallbacks(ISHIPActions)" />
    public interface ISHIPActions
    {
        /// <summary>
        /// Method invoked when associated input action "TURN" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTURN(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "ROLL" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnROLL(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "DRIVE" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnDRIVE(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "BRAKE" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnBRAKE(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LOOK" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLOOK(InputAction.CallbackContext context);
    }
}
